version: '3'
services:

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./html:/var/www/html
      - ./css:/var/www/html/css
      - ./js:/var/www/html/js
      - ./img:/var/www/html/img

    ports:
      - 80:80
      - 443:443 # Para futuro ssl (https)

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: xpto
      MYSQL_DATABASE: xpto
      MYSQL_USER: xpto
      MYSQL_PASSWORD: xpto

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=xpto
    depends_on:
      - db
